// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCg-EQFkEtuQp_XpAVaQMl8OIelXKQirXk',
    appId: '1:501362544704:web:4c7cc679e86e0aa6f88fa5',
    messagingSenderId: '501362544704',
    projectId: 'e-commerce-33a32',
    authDomain: 'e-commerce-33a32.firebaseapp.com',
    storageBucket: 'e-commerce-33a32.firebasestorage.app',
    measurementId: 'G-DLM5Y3JQ6X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBwLQ41oiqCHze3td5aa8GgzYu7hqqPfwQ',
    appId: '1:501362544704:android:78003128a50e2ff6f88fa5',
    messagingSenderId: '501362544704',
    projectId: 'e-commerce-33a32',
    storageBucket: 'e-commerce-33a32.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCEhgVHNexzSoi0GSfb8A_Y5Y5QYf3aSog',
    appId: '1:501362544704:ios:034358afdc20cbdbf88fa5',
    messagingSenderId: '501362544704',
    projectId: 'e-commerce-33a32',
    storageBucket: 'e-commerce-33a32.firebasestorage.app',
    androidClientId: '501362544704-86jakd9pr9f718d5k05j49b50102hta9.apps.googleusercontent.com',
    iosClientId: '501362544704-fook333s06l43ugiie6kjc0lt90b086c.apps.googleusercontent.com',
    iosBundleId: 'com.ecommerceappclient.ecommerceAppClient',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCg-EQFkEtuQp_XpAVaQMl8OIelXKQirXk',
    appId: '1:501362544704:web:e570f0f6f1c907c3f88fa5',
    messagingSenderId: '501362544704',
    projectId: 'e-commerce-33a32',
    authDomain: 'e-commerce-33a32.firebaseapp.com',
    storageBucket: 'e-commerce-33a32.firebasestorage.app',
    measurementId: 'G-EHXWW8VNW2',
  );

}